-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 18:21:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(30) NULL,
  `Área` VARCHAR(45) NULL,
  `Concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` VARCHAR(9) NOT NULL,
  `FechaNacimiento` DATETIME NULL,
  `Nombre` VARCHAR(45) NULL,
  `CabezaFamilia` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `CabezaFamilia_idx` (`CabezaFamilia` ASC) VISIBLE,
  CONSTRAINT `CabezaFamilia`
    FOREIGN KEY (`CabezaFamilia`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Longitud` INT NULL,
  `Carriles` INT NULL,
  `NombreZona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `NombreZona_idx` (`NombreZona` ASC) VISIBLE,
  CONSTRAINT `NombreZona`
    FOREIGN KEY (`NombreZona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Construcción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Construcción` (
  `Número` INT NOT NULL,
  `NombreCalle` VARCHAR(45) NOT NULL,
  `Superficie` FLOAT NULL,
  PRIMARY KEY (`Número`, `NombreCalle`),
  INDEX `NombreCalle_idx` (`NombreCalle` ASC) VISIBLE,
  CONSTRAINT `NombreCalle`
    FOREIGN KEY (`NombreCalle`)
    REFERENCES `mydb`.`Calle` (`Nombre`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivienda` (
  `Numero` INT NOT NULL,
  `DNI Propietario` VARCHAR(9) NULL,
  `Numero Habitaciones` INT NULL,
  PRIMARY KEY (`Numero`),
  INDEX `DNI Propietario_idx` (`DNI Propietario` ASC) VISIBLE,
  CONSTRAINT `Numero`
    FOREIGN KEY (`Numero`)
    REFERENCES `mydb`.`Construcción` (`Número`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DNI Propietario`
    FOREIGN KEY (`DNI Propietario`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Numero` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Numero`),
  CONSTRAINT `Numero`
    FOREIGN KEY (`Numero`)
    REFERENCES `mydb`.`Construcción` (`Número`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Letra` VARCHAR(1) NOT NULL,
  `Planta` INT NOT NULL,
  `Numero Bloque` INT NOT NULL,
  `DNI Propietario` VARCHAR(9) NULL,
  PRIMARY KEY (`Letra`, `Planta`, `Numero Bloque`),
  INDEX `Numero_idx` (`Numero Bloque` ASC) VISIBLE,
  INDEX `Propietario DNI_idx` (`DNI Propietario` ASC) VISIBLE,
  CONSTRAINT `Numero`
    FOREIGN KEY (`Numero Bloque`)
    REFERENCES `mydb`.`Bloque` (`Numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Propietario DNI`
    FOREIGN KEY (`DNI Propietario`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona_Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_Piso` (
  `Letra` VARCHAR(1) NOT NULL,
  `Planta` INT NOT NULL,
  `Número` INT NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Letra`, `Planta`, `Número`, `DNI`),
  INDEX `Planta_idx` (`Planta` ASC) VISIBLE,
  INDEX `Número_idx` (`Número` ASC) VISIBLE,
  INDEX `DNI_idx` (`DNI` ASC) VISIBLE,
  CONSTRAINT `Letra`
    FOREIGN KEY (`Letra`)
    REFERENCES `mydb`.`Piso` (`Letra`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Planta`
    FOREIGN KEY (`Planta`)
    REFERENCES `mydb`.`Piso` (`Planta`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `Número`
    FOREIGN KEY (`Número`)
    REFERENCES `mydb`.`Piso` (`Numero Bloque`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona_Vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_Vivienda` (
  `Número` INT NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Número`, `DNI`),
  INDEX `DNI_idx` (`DNI` ASC) VISIBLE,
  CONSTRAINT `Número`
    FOREIGN KEY (`Número`)
    REFERENCES `mydb`.`Vivienda` (`Numero`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Persona_Piso_BEFORE_INSERT` BEFORE INSERT ON `Persona_Piso` FOR EACH ROW
BEGIN
	IF (NEW.DNI IN (SELECT DNI
    FROM Persona_Vivienda)) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Persona ya viviendo en una vivienda';
	END IF;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Persona_Vivienda_BEFORE_INSERT` BEFORE INSERT ON `Persona_Vivienda` FOR EACH ROW
BEGIN
    IF (NEW.DNI IN (SELECT DNI
    FROM Persona_Piso)) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Persona viviendo en un piso';
    END IF;
END$$


DELIMITER ;
